ALTER TABLE "GameSession"
ADD COLUMN "prizePerCartela" DECIMAL(12,2) NOT NULL DEFAULT 8,
ADD COLUMN "companyFeePerCartela" DECIMAL(12,2) NOT NULL DEFAULT 2,
ADD COLUMN "companyRevenue" DECIMAL(12,2) NOT NULL DEFAULT 0;

ALTER TABLE "GameSession"
ALTER COLUMN "entryFee" SET DEFAULT 10,
ALTER COLUMN "prizeAmount" SET DEFAULT 0;
